-- Teakkuzz Cafe menu — run in Supabase SQL Editor to replace the sample menu
-- Safe: order_items store item names, not menu_item IDs

delete from menu_items;
delete from menu_categories;

insert into menu_categories (name, sort_order) values
  ('Cold Coffee', 1),
  ('Coffee / Hot', 2),
  ('Tea', 3),
  ('Shakes', 4),
  ('Coolers', 5),
  ('Noodles', 6),
  ('Pasta', 7),
  ('Burger', 8),
  ('Grilled Sandwiches', 9),
  ('Sub Sandwiches', 10),
  ('Wrap', 11),
  ('Fries', 12),
  ('Extra', 13),
  ('Add-ons', 14);

insert into menu_items (category_id, name, description, price, image_url)
select c.id, v.name, v.description, v.price, v.image_url
from (values
  ('Cold Coffee', 'Classic Cold Coffee', '', 89, '/menu/items/classic-cold-coffee.jpg'),
  ('Cold Coffee', 'Iced Americano', '', 99, '/menu/items/iced-americano.jpg'),
  ('Cold Coffee', 'Iced Mocha', '', 109, '/menu/items/iced-mocha.jpg'),
  ('Cold Coffee', 'Caramel', '', 129, '/menu/items/caramel.jpg'),
  ('Cold Coffee', 'Tiramisu', '', 139, '/menu/items/tiramisu.jpg'),
  ('Cold Coffee', 'Hazelnut', '', 149, '/menu/items/hazelnut.jpg'),
  ('Cold Coffee', 'Premium Cold Coffee', '', 149, '/menu/items/premium-cold-coffee.jpg'),
  ('Cold Coffee', 'Vietnamese Cold Coffee', '', 149, '/menu/items/vietnamese-cold-coffee.jpg'),
  ('Coffee / Hot', 'Cappuccino', '', 99, '/menu/items/cappuccino.jpg'),
  ('Coffee / Hot', 'Espresso', '', 99, '/menu/items/espresso.jpg'),
  ('Coffee / Hot', 'Americano', '', 99, '/menu/items/americano.jpg'),
  ('Coffee / Hot', 'Coffee Latte', '', 119, '/menu/items/coffee-latte.jpg'),
  ('Coffee / Hot', 'Hot Chocolate', '', 149, '/menu/items/hot-chocolate.jpg'),
  ('Tea', 'Kadak Chai', '', 29, '/menu/items/kadak-chai.jpg'),
  ('Tea', 'Masala Chai', '', 30, '/menu/items/masala-chai.jpg'),
  ('Tea', 'Adarak Elaichi Chai', '', 30, '/menu/items/adarak-elaichi-chai.jpg'),
  ('Tea', 'Gud Wali Chai', '', 36, '/menu/items/gud-wali-chai.jpg'),
  ('Tea', 'Haldi Chai', '', 36, '/menu/items/haldi-chai.jpg'),
  ('Tea', 'Green Tea', '', 29, '/menu/items/green-tea.jpg'),
  ('Tea', 'Green Tea with Honey', '', 39, '/menu/items/green-tea-with-honey.jpg'),
  ('Tea', 'Honey Ginger Lemon Tea', '', 39, '/menu/items/honey-ginger-lemon-tea.jpg'),
  ('Shakes', 'Korean Banana', '', 89, '/menu/items/korean-banana.jpg'),
  ('Shakes', 'Alphonso Mango', '', 99, '/menu/items/alphonso-mango.jpg'),
  ('Shakes', 'Oreo Shake', '', 119, '/menu/items/oreo-shake.jpg'),
  ('Shakes', 'Kit-Kat Shake', '', 129, '/menu/items/kit-kat-shake.jpg'),
  ('Shakes', 'Strawberry Love', '', 129, '/menu/items/strawberry-love.jpg'),
  ('Shakes', 'Mixed Berry', '', 139, '/menu/items/mixed-berry.jpg'),
  ('Coolers', 'Mint Mojito', '', 99, '/menu/items/mint-mojito.jpg'),
  ('Coolers', 'Spicy Lemonade', '', 99, '/menu/items/spicy-lemonade.jpg'),
  ('Coolers', 'Watermelon', '', 99, '/menu/items/watermelon.jpg'),
  ('Coolers', 'Spicy Mango (Aam Panna)', '', 99, '/menu/items/spicy-mango-aam-panna.jpg'),
  ('Coolers', 'Chilli Guava', '', 99, '/menu/items/chilli-guava.jpg'),
  ('Coolers', 'Green Apple', '', 99, '/menu/items/green-apple.jpg'),
  ('Coolers', 'Passion Fruit', '', 99, '/menu/items/passion-fruit.jpg'),
  ('Coolers', 'Blueberry', '', 99, '/menu/items/blueberry.jpg'),
  ('Coolers', 'Peach', '', 99, '/menu/items/peach.jpg'),
  ('Coolers', 'Iced Tea', '', 99, '/menu/items/iced-tea.jpg'),
  ('Coolers', 'Blue Lagoon', '', 99, '/menu/items/blue-lagoon.jpg'),
  ('Coolers', 'Peach Iced Tea', '', 99, '/menu/items/peach-iced-tea.jpg'),
  ('Noodles', 'Maggi', '', 79, '/menu/items/maggi.jpg'),
  ('Noodles', 'Yippee', '', 79, '/menu/items/yippee.jpg'),
  ('Noodles', 'Wai Wai', '', 79, '/menu/items/wai-wai.jpg'),
  ('Pasta', 'White Sauce Pasta', '', 149, '/menu/items/white-sauce-pasta.jpg'),
  ('Pasta', 'Red Sauce Pasta', '', 149, '/menu/items/red-sauce-pasta.jpg'),
  ('Pasta', 'Pink Sauce Pasta', '', 159, '/menu/items/pink-sauce-pasta.jpg'),
  ('Burger', 'Aloo Tikki Burger', '', 69, '/menu/items/aloo-tikki-burger.jpg'),
  ('Burger', 'Veg Crispy Burger', '', 99, '/menu/items/veg-crispy-burger.jpg'),
  ('Burger', 'Schezwan Burger', '', 89, '/menu/items/schezwan-burger.jpg'),
  ('Burger', 'Achari Masti Burger', '', 99, '/menu/items/achari-masti-burger.jpg'),
  ('Burger', 'Peri-Peri Nachos Burger', '', 109, '/menu/items/peri-peri-nachos-burger.jpg'),
  ('Burger', 'Tandoori Paneer Burger', '', 119, '/menu/items/tandoori-paneer-burger.jpg'),
  ('Grilled Sandwiches', 'Rainbow Sandwich', '', 109, '/menu/items/rainbow-sandwich.jpg'),
  ('Grilled Sandwiches', 'Moms Kitchen Magic Sandwich', 'Teakkuz Special', 119, '/menu/items/moms-kitchen-magic-sandwich.jpg'),
  ('Grilled Sandwiches', 'Cheese Corn Sandwich', '', 129, '/menu/items/cheese-corn-sandwich.jpg'),
  ('Grilled Sandwiches', 'Classic Paneer Sandwich', '', 139, '/menu/items/classic-paneer-sandwich.jpg'),
  ('Sub Sandwiches', 'Garden Fresh', 'Teakkuz Special', 139, '/menu/items/garden-fresh.jpg'),
  ('Sub Sandwiches', 'Schezwan Paneer Sub', '', 169, '/menu/items/schezwan-paneer-sub.jpg'),
  ('Wrap', 'Aloo Tikki Wrap', '', 109, '/menu/items/aloo-tikki-wrap.jpg'),
  ('Wrap', 'Veggie Delite Wrap', '', 99, '/menu/items/veggie-delite-wrap.jpg'),
  ('Wrap', 'Achari Paneer Wrap', '', 129, '/menu/items/achari-paneer-wrap.jpg'),
  ('Wrap', 'Paneer Wrap', '', 119, '/menu/items/paneer-wrap.jpg'),
  ('Fries', 'Classic Salted Fries', '', 89, '/menu/items/classic-salted-fries.jpg'),
  ('Fries', 'Peri-Peri Fries', '', 99, '/menu/items/peri-peri-fries.jpg'),
  ('Fries', 'Chatkara Fries', '', 109, '/menu/items/chatkara-fries.jpg'),
  ('Fries', 'Cheese Loaded Fries', '', 129, '/menu/items/cheese-loaded-fries.jpg'),
  ('Fries', 'Pizza Pocket', '', 119, '/menu/items/pizza-pocket.jpg'),
  ('Fries', 'Cheese Corn', '', 109, '/menu/items/cheese-corn.jpg'),
  ('Extra', 'Bun Maska', '', 49, '/menu/items/bun-maska.jpg'),
  ('Extra', 'Mix Salad Bowl', '', 89, '/menu/items/mix-salad-bowl.jpg'),
  ('Extra', 'Sweet Corn', '', 119, '/menu/items/sweet-corn.jpg'),
  ('Add-ons', 'Dip', 'Extra', 15, '/menu/items/dip.jpg'),
  ('Add-ons', 'Cheese Slice', 'Extra', 20, '/menu/items/cheese-slice.jpg'),
  ('Add-ons', 'Honey', 'Extra', 20, '/menu/items/honey.jpg'),
  ('Add-ons', 'Espresso Shot', 'Extra', 69, '/menu/items/espresso-shot.jpg')
) as v(cat, name, description, price, image_url)
join menu_categories c on c.name = v.cat;
